// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU_System;

/************************************************************/
/**
 * 
 */
public class Coordinate {

	private int x;
	private int y = 0;
	private int z;
	private boolean isCovered;
	private boolean isObstacle;

	public Coordinate(int x, int y, int z) {
		this.x = x;
		this.y = y;
		this.z = z;
		isCovered = false;
		isObstacle = false;
	}

	public Coordinate(int x, int z) {
		this.x = x;
		this.z = z;
		isCovered = false;
		isObstacle = false;
	}

	void setCovered(boolean b) {
		isCovered = b;
	}

	void setObstacle(boolean b) {
		isObstacle = b;
	}

	boolean isCovered() {
		return isCovered;
	}

	boolean isObstacle() {
		return isObstacle;
	}
	
	int getX(){ return x; }
	int getY(){ return y; }
	int getZ(){ return z; }
};
