// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU_System;

/************************************************************/
/**
 * 
 */
public class Coordinate {

	private double x;
	private double y = 0;
	private double z;
	private boolean isCovered;
	private boolean isObstacle;

	public Coordinate(double x, double y, double z) {
		this.x = x;
		this.y = y;
		this.z = z;
		isCovered = false;
		isObstacle = false;
	}

	public Coordinate(double x, double z) {
		this.x = x;
		this.z = z;
		isCovered = false;
		isObstacle = false;
	}

	void setCovered(boolean b) {
		isCovered = b;
	}

	void setObstacle(boolean b) {
		isObstacle = b;
	}

	boolean isCovered() {
		return isCovered;
	}

	boolean isObstacle() {
		return isObstacle;
	}
	
	double getX(){ return x; }
	double getY(){ return y; }
	double getZ(){ return z; }
};
