// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU_System;

/************************************************************/
/**
 * 
 */
public enum MovementEnum {
	/**
	 * 
	 */
	ROTATE,
	/**
	 * 
	 */
	MOVE,
	/**
	 * 
	 */
	ROTATE_MOVE,
	/**
	 * 
	 */
	MOVE_DEST;
};
