// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU_System;

import RootElement.ROVU_System.Coordinate;
import RootElement.ROVU_System.MovementEnum;
import RootElement.ROVU_System.Task;

/************************************************************/
/**
 * 
 */
public class Movement extends Task {
	/**
	 * 
	 */
	private MovementEnum moveType;
	/**
	 * 
	 */
	private int direction;
	/**
	 * 
	 */
	private int distance;
	/**
	 * 
	 */
	private Coordinate destination;

	/**
	 * 
	 */
	public Movement() {
	}
};
