// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU_System;

import RootElement.ROVU_System.Task;

/************************************************************/
/**
 * 
 */
public class Picture extends Task {
	/**
	 * 
	 */
	private int direction;

	/**
	 * 
	 * @param direction 
	 */
	public Picture(int direction) {
	}
};
