// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU_System;

/************************************************************/
/**
 * 
 */
public enum RoverEnum {
	/**
	 * 
	 */
	CAMERA_ROVER,
	/**
	 * 
	 */
	SCOUTING_ROVER;
};
