// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU_System;

import RootElement.ROVU_System.TaskEnum;

/************************************************************/
/**
 * 
 */
public abstract class Task {
	/**
	 * 
	 */
	private TaskEnum type;

	/**
	 * 
	 */
	public Task() {
	}

	/**
	 * 
	 */
	public void performTask() {
	}
};
