// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU_System;

/************************************************************/
/**
 * 
 */
public class Zone {
	/**
	 * 
	 */
	private int id;
	private Coordinate[][] zoneGrid;

	public Zone(int id) {
		this.id = id;
	}

	public void setZoneGrid(Coordinate[][] zg) {
		zoneGrid = zg;
	}
	public Coordinate[][] getZoneGrid(){
		return zoneGrid;
	}
	public int getID(){
		return id;
	}

};
